const temp = [
  [
    [
      {
        moduleCode: 'CS1010',
        moduleCredit: '4',
        attributes: {su: true},
        gradeIdx: 0,
        isFlagged: false,
        isPrereqCleared: true,
        isPrereqInSameSem: false,
        isCoreqInSameSem: true,
        isPrecluAdded: false,
      },
      {
        moduleCode: 'CS2002',
        moduleCredit: '4',
        attributes: {su: true},
        gradeIdx: 0,
        isFlagged: false,
        isPrereqCleared: true,
        isPrereqInSameSem: false,
        isCoreqInSameSem: true,
        isPrecluAdded: false,
      },
      {
        moduleCode: 'CS2040',
        moduleCredit: '4',
        gradeIdx: 0,
        isFlagged: false,
        isPrereqCleared: true,
        isPrereqInSameSem: false,
        isCoreqInSameSem: true,
        isPrecluAdded: false,
      },
    ],
    [],
    [],
    [],
    {semModularCredit: 12},
    {semModularCredit: 0},
    {semModularCredit: 0},
    {semModularCredit: 0},
  ],
  [
    [],
    [],
    [],
    [],
    {semModularCredit: 0},
    {semModularCredit: 0},
    {semModularCredit: 0},
    {semModularCredit: 0},
  ],
  [
    [],
    [],
    [],
    [],
    {semModularCredit: 0},
    {semModularCredit: 0},
    {semModularCredit: 0},
    {semModularCredit: 0},
  ],
  [
    [],
    [],
    [],
    [],
    {semModularCredit: 0},
    {semModularCredit: 0},
    {semModularCredit: 0},
    {semModularCredit: 0},
  ],
  [
    [],
    [],
    [],
    [],
    {semModularCredit: 0},
    {semModularCredit: 0},
    {semModularCredit: 0},
    {semModularCredit: 0},
  ],
  {
    totalSU: 0,
    suUsed: 0,
    suLeft: 0,
    totalMCAdded: 12,
    totalMxP: 0,
    totalMCClearedInternal: 0,
    totalMCClearedExternal: 0,
    currentCap: 0,
    isDarkModeChecked: false,
    isDisplayed: [
      [true, true, false, false, false],
      [false, true, false, false, false],
      [false, true, false, false, false],
      [false, true, false, false, false],
      [false, true, false, false, false],
    ],
  },
];
